### ISSUE TITLE
Not an issue - a question - Why did you do this?

### ISSUE THREAD

**Issue by Dunaway-Group-LLC** [alexdebrie/serverless-flask#1]
Question may sound strange - the reasons behind it are that given the time and session limitions on AWS lambda, an interactive Flask app seems unusable on the platform.

But, knowing you are a smart guy, I'm assuming there's a use case

The only use case I've thought of is making the presentation of forms easier???

Writing about that on the serverless blog would be a service to the community

**Comment by alexdebrie** [comment]
Hi @lesatdgl! Good question. Flask actually works pretty well with Lambda. Each separate web request is a different Lambda invocation, so you don't run up against time limitations much. The benefits of using Flask is just the familiarity of using a web framework you already know while still getting the easy deploys and automatic scaling of Lambda.

I've written a large article about using Flask with Lambda [here](https://serverless.com/blog/flask-python-rest-api-serverless-lambda-dynamodb/).

Going to close this issue, but feel free to ask follow ups if you have them :)

**Comment by Dunaway-Group-LLC** [comment]
That's good to know - however, it seems there's no way to have a session
in that scenario? So each request would have to be a discrete, complete
transaction - right? Or am I making this too complicated?
Les Dunaway
770-490-7546



On Mon, Jul 9, 2018, at 05:51, Alex DeBrie wrote:
> Hi @lesatdgl[1]! Good question. Flask actually works pretty well with
> Lambda. Each separate web request is a different Lambda invocation,
> so you don't run up against time limitations much. The benefits of
> using Flask is just the familiarity of using a web framework you
> already know while still getting the easy deploys and automatic
> scaling of Lambda.> I've written a large article about using Flask with Lambda here[2].> Going to close this issue, but feel free to ask follow ups if you
> have them :)> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[3], or mute the thread[4].

Links:

  1. https://github.com/lesatdgl
  2. https://serverless.com/blog/flask-python-rest-api-serverless-lambda-dynamodb/
  3. https://github.com/alexdebrie/serverless-flask/issues/1#issuecomment-403424375

**Comment by alexdebrie** [comment]
Yea, you would need to use something like DynamoDB to store sessions, and pass it back and forth with each request.
